language: python
python:
  - "3.8"
#create requirements.txt file
before_install:
  - pip freeze --local > requirements.txt
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  # First sample run test on PIP version
  - pytest tests/test_src.py
notifications:
  email:
    - skizza8@gmail.com
