language: python
python:
  - "3.8"
services:
  - postgresql
env:
  global:
    - APP_SETTINGS ='testing'
# command to install dependencies
install:
  - pip install -r requirements.txt
  - "pip install coveralls"
before_script:
  - "psql -c 'create database teachershubdb;' -U postgres"
  - "psql -c 'create database teachershub_testdb;' -U postgres"
# command to run tests
script:
  # First sample run test on PIP version
  - pytest --cov-report term --cov=tests/

after_success:
  - coveralls
